AWSTemplateFormatVersion: '2010-09-09'
Description: Organization data collections.
Parameters:
  RoleARN:
    Type: String
    Description: ARN of the IAM role deployed in the management accounts which can retrieve AWS Org data.
  TaskQueuesUrl:
    Type: String
    Description: the Ques URL that will get the accounts messages, split by comers
  Suffix:
    Type: String
    Description: If this module needs to be made more than one a Suffix can be added
    Default: ''
  Schedule:
    Type: String
    Description: Cron job to trigger the lambda using cloudwatch event
    Default: "rate(14 days)"
Outputs:
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AWS-Organization-Account-Collector-Role${Suffix}"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /
      Policies:
        - PolicyName: "Assume-Management-Organization-Data-Role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "sts:AssumeRole"
                Resource:
                  Ref: RoleARN
        - PolicyName: "S3-Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: "Sqs-Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                 - sqs:SendMessage
                 - sqs:ReceiveMessage
                 - sqs:DeleteMessage
                 - sqs:GetQueueAttributes
                Resource: "*"
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "AWS-Organization-Account-Collector${Suffix}"
      Description: LambdaFunction of python3.8.
      Runtime: python3.8
      Code:
          ZipFile: |
            import boto3
            import logging
            import os

            def sqs_messege(account_id, QueueUrl):
                #posts messege to que
                client = boto3.client('sqs')
                

                response = client.send_message(
                    QueueUrl=QueueUrl,
                    MessageBody=account_id
                )
                return response


            def org_accounts():
              acount_ids = []
              ROLE_ARN = os.environ['ROLE_ARN']

              sts_connection = boto3.client('sts')
              acct_b = sts_connection.assume_role(
                    RoleArn=ROLE_ARN,
                    RoleSessionName="cross_acct_lambda"
              )
                        
              ACCESS_KEY = acct_b['Credentials']['AccessKeyId']
              SECRET_KEY = acct_b['Credentials']['SecretAccessKey']
              SESSION_TOKEN = acct_b['Credentials']['SessionToken']

              # create service client using the assumed role credentials
              client = boto3.client(
                    "organizations", region_name="us-east-1", #Using the Organization client to get the data. This MUST be us-east-1 regardless of region you have the lamda in
                    aws_access_key_id=ACCESS_KEY,
                    aws_secret_access_key=SECRET_KEY,
                    aws_session_token=SESSION_TOKEN,
              )
              paginator = client.get_paginator("list_accounts") #Paginator for a large list of accounts
              response_iterator = paginator.paginate()

              for account in response_iterator:
                  for ids in account['Accounts']:
                      acount_ids.append(ids)
              logging.info("AWS Org data Gathered")
              return acount_ids
            

            def lambda_handler(event, context):
                account_info = org_accounts()

                for account in account_info:
                    if  account['Status'] == 'ACTIVE':
                        try:
                            account_id = account['Id']
                            for que in os.environ.get("SQS_URL").split(","):
                              print(que)
                              sqs_messege(account_id, que)
                              logging.info(f"SQS message sent for {account_id} to TA")

                        except Exception as e:
                            pass
                            logging.warning("%s" % e)
                    else:
                        logging.info(f"account {account['Id']} is not active")

      Handler: 'index.lambda_handler'
      MemorySize: 2688
      Timeout: 600
      Role: 
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Environment:
        Variables:
          SQS_URL: !Ref TaskQueuesUrl
          ROLE_ARN: !Ref RoleARN
  CloudWatchTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Scheduler-For-Accounts
      Name: !Sub "Scheduler-For-Accounts${Suffix}"
      ScheduleExpression: !Ref Schedule
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - LambdaFunction
              - Arn
          Id: WeeklyTriggerForGetAccounts
  EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt CloudWatchTrigger.Arn